use enron;

db.messages.find({'headers.Message-ID': '<8147308.1075851042335.JavaMail.evans@thyme>'}, {_id: 0, 'headers.Message-ID': 1, 'headers.To': 1});
//{ "headers" : { "Message-ID" : "<8147308.1075851042335.JavaMail.evans@thyme>", "To" : [ "steven.kean@enron.com", "richard.shapiro@enron.com", "james.steffes@enron.com", "christi.nicolay@enron.com", "sarah.novosel@enron.com", "ray.alvarez@enron.com", "sscott3@enron.com", "joe.connor@enron.com", "dan.staines@enron.com", "steve.montovano@enron.com", "kevin.presto@enron.com", "rogers.herndon@enron.com", "mike.carson@enron.com", "john.forney@enron.com", "laura.podurgiel@enron.com", "gretchen.lotz@enron.com", "juan.hernandez@enron.com", "miguel.garcia@enron.com", "rudy.acevedo@enron.com", "heather.kroll@enron.com", "david.fairley@enron.com", "elizabeth.johnston@enron.com", "bill.rust@enron.com", "edward.baughman@enron.com", "terri.clynes@enron.com", "oscar.dalton@enron.com", "doug.sewell@enron.com", "larry.valderrama@enron.com", "nick.politis@enron.com", "fletcher.sturm@enron.com", "chris.dorland@enron.com", "jeff.king@enron.com", "john.kinser@enron.com", "matt.lorenz@enron.com", "patrick.hansen@enron.com", "lloyd.will@enron.com", "dduaran@enron.com", "john.lavorato@enron.com", "louise.kitchen@enron.com", "greg.whalley@enron.com" ] } }

// question-3: update
db.messages.update({'headers.Message-ID': '<8147308.1075851042335.JavaMail.evans@thyme>'}, {$push: {'headers.To': 'mrpotatohead@mongodb.com'}});
//WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })

// verify the result
db.messages.find({'headers.Message-ID': '<8147308.1075851042335.JavaMail.evans@thyme>'}, {_id: 0, 'headers.Message-ID': 1, 'headers.To': 1});
//{ "headers" : { "Message-ID" : "<8147308.1075851042335.JavaMail.evans@thyme>", "To" : [ "steven.kean@enron.com", "richard.shapiro@enron.com", "james.steffes@enron.com", "christi.nicolay@enron.com", "sarah.novosel@enron.com", "ray.alvarez@enron.com", "sscott3@enron.com", "joe.connor@enron.com", "dan.staines@enron.com", "steve.montovano@enron.com", "kevin.presto@enron.com", "rogers.herndon@enron.com", "mike.carson@enron.com", "john.forney@enron.com", "laura.podurgiel@enron.com", "gretchen.lotz@enron.com", "juan.hernandez@enron.com", "miguel.garcia@enron.com", "rudy.acevedo@enron.com", "heather.kroll@enron.com", "david.fairley@enron.com", "elizabeth.johnston@enron.com", "bill.rust@enron.com", "edward.baughman@enron.com", "terri.clynes@enron.com", "oscar.dalton@enron.com", "doug.sewell@enron.com", "larry.valderrama@enron.com", "nick.politis@enron.com", "fletcher.sturm@enron.com", "chris.dorland@enron.com", "jeff.king@enron.com", "john.kinser@enron.com", "matt.lorenz@enron.com", "patrick.hansen@enron.com", "lloyd.will@enron.com", "dduaran@enron.com", "john.lavorato@enron.com", "louise.kitchen@enron.com", "greg.whalley@enron.com", "mrpotatohead@mongodb.com" ] } }